client/package-lock.json, client/package.json, client/src/App.jsx, client/src/Redux/store.js, client/src/components/ErrorFallback.jsx, client/src/components/SongGallary.jsx, client/src/main.jsx, client/src/pages/ArtistPage.jsx, client/src/pages/Home.jsx, client/src/pages/SongPage.jsx
create basic react structure done , i install the error boundry and try to test it in small example and now i comment it ,
=> create basic react structure done

README.md, server/config/db.js, server/package-lock.json, server/package.json, server/server.js
- changed the path to the config file in server.js (before it didn't reach it)
- created a new config.env file based on what Toni already did (it contained NODE_ENV and PORT)
- created a MongoDB Atlas instance
- saved mongodb user name + password in .env
- connected to db
**- Added a function that handles unhandled rejections to server.js - it logs the error and exits from the server. THIS WAS NOT A PART OF THE TASK**
=> 12 basic configuration env atlas

server/config/db.js, server/routes/translationRoutes.js, server/utils/translatingFunction.js, server/utils/translationBySongName.js
To check this function that it work need function to get lyrics from API if no lyrics in database. I tested this function on song and artist that I stored in my mongoDB, so it's works. Will wait for lyricsAPI to test full functionality.
=> 17_Translation_by_song_name

server/scripts/config.script.sh
env script updated with spotify client id and secret variables.
=> 125_spotify client id and secret added to env generation script

client/src/api/songDataApiSlice.js, client/src/components/LanguagesSign/LanguagesSign.jsx, client/src/components/SongListItem/SongListItem.jsx, client/src/components/TraslationSymbolsGroup/TranslationSymbolsGroup.jsx, client/src/components/songDetails/SongDetails.jsx, client/src/pages/ArtistPage/ArtistPage.jsx, client/src/pages/SongPage.jsx
Path => components -> TraslationSymbolsGroup -> TranslationSymbolsGroup -> Added a prop : originalLanguage , it will be sent to SongListItem
in SongListItem we used useSongDataMutation hook from rtk query  to fetch the data and we called the function  in a useEffect 
and gave it an object with the song and artist from the SongListItem props so they are dynamic
and then we used the TranslationSymbolsGroup component in SongListItem and passed the prop originalLanguage to be the fetched language.
We also in line 35 added the coverArt of each song beside the name of the song.
=> fixed translationSymbol in Artist Page

server/scrapping/scrappingGoogleLyrics.js, server/utils/openAiTranslation.js
Fixed scraping for all the songs
=> fixed scraping

client/src/pages/SearchResults/SearchResults.jsx, server/scrapping/scrappingGoogleLyrics.js
in server side -> scrapping -> scrappingGoogleLyrics.js
Some songs couldnt be scrapped because the site to scrap from is not found 
so i added two more sites to fix this issue , added one hebrew site and one arabic site.
=> Bugs fixing

client/package-lock.json, server/models/CoverSong.js, server/models/Song.js
=> Backend hussein

client/src/main.jsx, server/server.js
clean the rapper from main.jsx
=> login page2

server/controllers/CoverSongController.js, server/controllers/songsController.js, server/models/CoverSong.js, server/routes/CoverSongRoute.js
Cover song and cover song controller and route
=> Cover song and cover song controller and route

server/controllers/CoverSongController.js, server/models/CoverSong.js, server/models/Song.js, server/routes/CoverSongRoute.js, server/server.js
continued working on CoverSongController
=> continued working on CoverSongController

client/src/pages/CoverPage/CoverPage.jsx, client/src/pages/TranslatingPage.jsx, server/controllers/CoverSongController.js, server/models/CoverSong.js
updated coverSongController.js
=> updated coverSongController

client/src/api/addCoverToSongApi.js, client/src/components/UploadButton/UploadCoverModal.jsx, client/src/pages/CoverPage/CoverPage.jsx, client/src/pages/CoverPage/CoverPage.styles.js, client/src/pages/SongPage.jsx, server/controllers/songsController.js, server/middleware/errorHandler.js, server/models/CoverSong.js, server/routes/CoverSongRoute.js, server/routes/songsRoutes.js
Added in SongPage new component and new rtk query endpoint and updated coverPage to be dynamic
=> Cover component

client/src/api/addCoverToSongApi.js, client/src/components/UploadButton/UploadCoverModal.jsx, client/src/pages/SongPage.jsx, server/controllers/CoverSongController.js, server/models/CoverSong.js
sorted cover songs when we add new one to be on top
and added to the schema of coverSong a reference to originalSongId
=> sorted cover songs when we add new one to be on top

client/src/api/viewsAndLikesApi.js, client/src/components/Youtube/Youtube.jsx, client/src/components/Youtube/YoutubeStyle.jsx, client/src/pages/CoverPage/CoverPage.jsx, server/controllers/CoverSongController.js, server/routes/CoverSongRoute.js
added views counter in frontend and backend
=> added views counter in frontend

client/src/components/General/ImgCard.jsx, client/src/pages/PlaylistPage/PlaylistPage.jsx, client/src/pages/PlaylistPage/PlaylistPage.styled.js
=> Playlist frontend

client/src/api/viewsAndLikesApi.js, client/src/pages/CoverPage/CoverPage.jsx, server/controllers/CoverSongController.js, server/routes/CoverSongRoute.js
=> added like

client/src/pages/CoverPage/CoverPage.jsx
=> Removed extra

client/src/api/viewsAndLikesApi.js, client/src/pages/CoverPage/CoverPage.jsx
=> fixed views rendering

client/src/pages/Login/Login.jsx, client/src/pages/Login/LoginPageStyles.js
=> fixed login page

server/constants/playlistData.js
This pull request addresses the bug reported by Hasan regarding " Hasan Omar: only the first playlist from each language works
Hasan Omar: and if u go to one of the broken playlist , all of the site breaks , even the token , you have to restart the server to fix it"
=> add id to all playlists

server/controllers/playlistController.js
change in backend replace fetch with axios in playlistController.js
=> Playlist feature

client/src/components/Header/Header.css, client/src/components/Header/Header.jsx, client/src/components/Header/HeaderStyle.jsx, client/src/components/HomeSerchBar/HomeSearchBarStyle.js, client/src/components/SongListItem/SongListItem.jsx, client/src/components/SongListItem/SongListItem.styled.js, client/src/components/Tagline/Tagline.styled.js, client/src/components/ThreeLnagNames/ThreeLangNames.jsx, client/src/components/ThreeLnagNames/ThreeLangNames.styled.js, client/src/components/authUtils.js, client/src/pages/ArtistPage/ArtistPage.jsx, client/src/pages/ArtistPage/ArtistPage.styled.js, server/middleware/AuthSetup.js, server/models/User.js
=> Song page covers

client/src/components/shareButton/ShareButton.jsx, client/src/pages/CoverPage/CoverPage.jsx, client/src/pages/CoverPage/CoverPage.styles.js
=> sharebuttonrefctor

client/src/api/viewsAndLikesApi.js, client/src/components/CommentSection/CommentSection.jsx, client/src/pages/CoverPage/CoverPage.jsx, server/controllers/commentsController.js, server/models/CoverSongComments.js, server/routes/coverSongCommentsRoute.js
=> Cover page

client/src/components/UploadButton/UploadCoverButton.jsx, client/src/components/UploadButton/UploadCoverModal.jsx, client/src/components/UploadButton/uploadCoverButton.styles.js, client/src/components/UploadButton/uploadCoverModal.styles.js, server/controllers/CoverSongController.js
message and ui is ready, no repetition allowed of cover and the youtube URL is validated before adding
=> add message cover already added and validate youtube url

client/src/components/AddComment/AddComment.jsx, client/src/components/AddComment/AddCommentStyles.js, client/src/components/CommentSection/CommentSectionStyles.js, client/src/components/CoverPageYoutube/CoverPageYoutube.jsx, client/src/components/CoverPageYoutube/CoverPageYoutubeStyle.js, client/src/components/UploadButton/UploadCoverModal.jsx, client/src/pages/CoverPage/CoverPage.jsx, client/src/pages/CoverPage/CoverPage.styles.js
cover page desktop responsovie without share btn
=> coverPage desktop - without share btn

client/src/App.jsx, client/src/components/Animation/Animation.component.jsx, client/src/components/CoverSongData/CoverSongData.jsx, client/src/components/SongCoverNew/SongCoverNew.jsx, client/src/pages/CoverPage/CoverPage.jsx
=> added params to coverPage

client/src/components/CoverPageYoutube/CoverPageYoutubeStyle.js, client/src/components/SongAndSingerContainer/SongAndSingerContainerStyles.js
added cursor pointer for stuff
=> added cursor pointer for stuff

client/src/components/CoverSongData/CoverSongDataStyles.js, client/src/components/Lyrics/Lyrics.jsx, client/src/components/SongCoverNew/SongCoverStyles.js
fixed song page styles for imgs
=> fixed song page styles for imgs

server/scrapping/scrappingTopHebrewSongs.js
changed scrappingTopHebrew and arabic scrapping
=> changed scrappingTopHebrew and arabic scrapping

server/scrapping/scrappingTopHebrewSongs.js
changed scrappingTopHebrewSongs scrapppppping dir
=> changed scrappingTopHebrewSongs scrapppppping dir

client/src/components/TopSongGallary/TopSongGallary.jsx, client/src/pages/Home.jsx
=> fixed animation in homepage

client/src/components/topPlaylist/PlaylistStyle.jsx
=> fixed responsive to no cover

client/src/components/SongGallery/ImageBoxWithDetails.jsx, client/src/components/SongGallery/SongGallery.jsx, client/src/components/SongGallery/SongGalleryStyle.js, client/src/components/TopSongGallary/TopSongGallary.jsx, client/src/pages/Home.jsx, client/src/pages/HomeStyles.js, client/src/pages/NotFoundPageStyles.js
generic song gallery component
=> generic song gallery component

client/src/pages/NotFoundPage.jsx
=> fixed not found page

client/src/components/Animation/Animation.styled.js, client/src/components/SongGallery/SongGalleryStyle.js, client/src/components/topPlaylist/PlaylistStyle.jsx
=> Home covers

client/src/components/HomeSongGallery/HomeSongGallery.jsx, client/src/components/SongGallery/ImageBoxWithDetails.jsx, client/src/components/SongGallery/SongGallery.jsx, client/src/pages/Home.jsx
=> refactored Home page

client/src/api/songDataApiSlice.js, client/src/components/HomeSongGallery/HomeSongGallery.jsx, client/src/components/ResultsCard/ResultsCard.jsx, client/src/components/SongGallery/ImageBoxWithDetails.jsx, client/src/components/SongListItem/SongListItem.jsx, client/src/pages/ArtistPage/ArtistPage.jsx, client/src/pages/SearchResults/SearchResults.jsx, client/src/pages/TranslatingPage.jsx, server/controllers/artistsController.js, server/controllers/songsController.js, server/controllers/topSongsController.js, server/models/Song.js, server/models/TopSongs.js, server/utils/createObjectFromQuery.js
added id for each song to fix scrapping
=> added id for each song to fix scrapping

client/src/pages/CoverPage/CoverPage.jsx
fixed coverpage navigate to original song
=> fixed coverpage navigate to original song

server/scrapping/scrappingTopArabicSongs.js, server/utils/paramEncoder.js
removed  and commercial word from song and artist name
=> removed  and commercial word from song and artist name

client/src/components/SongGallery/ImageBoxWithDetails.jsx, client/src/components/SongGallery/SongGallery.jsx, client/src/components/SongGallery/SongGalleryStyle.js
Home covershome covers css desktop - not finished
=> home covers css desktop - not finished

client/src/components/Header/HeaderStyle.jsx, client/src/pages/Login/Login.jsx
=> changed fb login msg

client/src/components/Lyrics/LyricsStyle.jsx, server/controllers/songsController.js, server/utils/detectLang.js
fixed original language for english and css
=> fixed original language for english and css
